### ISSUE TITLE
Deploy netlify

### ISSUE THREAD

**Issue by Kax-y** [KanSync/kansync-portal#44]

**Comment by amermsl92** [comment]
Netlify is a cloud computing company that provides web hosting and automation services for modern web applications.

Deployment Steps:
Log in to Netlify:
Go to the Netlify website (https://www.netlify.com/) and log in with your account credentials.

Connect Your Git Repository:
- Once logged in, click on "New Site from Git" on the Netlify dashboard.
- Choose your Git platform (e.g., GitHub).
- Authorize Netlify to access the repository and select the repository needed to deploy.

Configure Build Settings:
Netlify needs to know how to build your React application. It will try to detect common build configurations by default, but you can customize this if needed.

Set the following build settings:
Build Command: This is a typical ”npm run build” for React applications.
Publish Directory: Specify the directory where the build output is stored, which is usually “build” for a Create React App project.
*Note that these fields Netlify fill automatically with standard inputs. Can be left without touching 

Environment Variables:
If the React app relies on environment variables (e.g., API keys), they can be set in the Netlify dashboard under "Site settings" > "Build & deploy" > "Environment Variables."

Deploy Your Site:
Click the "Deploy Site" button in the Netlify dashboard.
Netlify will initiate the build process, running the build command specified in your build settings.

Site URL:
Once the build is complete, Netlify will provide a URL where the React application is live. It will be something like ”https://your-site-name.netlify.app”.

Custom Domain (Optional):
If we have a custom domain, we can set it up in Netlify under "Site settings" > "Domain management."

Continuous Deployment:
Netlify can automatically redeploy the site whenever a change is being pushed to the Git repository. 

Testing:
Test your deployed React application on the provided Netlify URL to ensure everything is working as expected.

Monitoring and Analytics (Optional):
use Netlify's monitoring and analytics tools to track the site's performance and visitor metrics.
